import type { Config } from "tailwindcss";

const config: Config = {
  content: [
      "./pages/**/*.{js,ts,jsx,tsx,mdx}",
          "./components/**/*.{js,ts,jsx,tsx,mdx}",
              "./app/**/*.{js,ts,jsx,tsx,mdx}",
                ],
                  theme: {
                      extend: {
                            colors: {
                                    border: "hsl(var(--border))",
                                            background: "hsl(var(--background))",
                                                    foreground: "hsl(var(--foreground))",
                                                            primary: {
                                                                      DEFAULT: "hsl(var(--primary))",
                                                                                foreground: "hsl(var(--primary-foreground))",
                                                                                        },
                                                                                                secondary: {
                                                                                                          DEFAULT: "hsl(var(--secondary))",
                                                                                                                    foreground: "hsl(var(--secondary-foreground))",
                                                                                                                            },
                                                                                                                                    muted: {
                                                                                                                                              DEFAULT: "hsl(var(--muted))",
                                                                                                                                                        foreground: "hsl(var(--muted-foreground))",
                                                                                                                                                                },
                                                                                                                                                                        accent: {
                                                                                                                                                                                  DEFAULT: "hsl(var(--accent))",
                                                                                                                                                                                            foreground: "hsl(var(--accent-foreground))",
                                                                                                                                                                                                    },
                                                                                                                                                                                                            // Legacy support for your existing components
                                                                                                                                                                                                                    "neon-green": "#10B981",
                                                                                                                                                                                                                            "neon-blue": "#3B82F6",
                                                                                                                                                                                                                                    "neon-pink": "#EC4899",
                                                                                                                                                                                                                                            "cyber-gray": "#18181B",
                                                                                                                                                                                                                                                    "cyber-muted": "#A1A1AA",
                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                backgroundImage: {
                                                                                                                                                                                                                                                                        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                    animation: {
                                                                                                                                                                                                                                                                                            float: "float 6s ease-in-out infinite",
                                                                                                                                                                                                                                                                                                    "pulse-glow": "pulse-glow 2s ease-in-out infinite",
                                                                                                                                                                                                                                                                                                            shimmer: "shimmer 2s infinite",
                                                                                                                                                                                                                                                                                                                    gradient: "gradient-shift 3s ease infinite",
                                                                                                                                                                                                                                                                                                                            "spin-slow": "spin-slow 3s linear infinite",
                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                        keyframes: {
                                                                                                                                                                                                                                                                                                                                                float: {
                                                                                                                                                                                                                                                                                                                                                          "0%, 100%": { transform: "translateY(0px)" },
                                                                                                                                                                                                                                                                                                                                                                    "50%": { transform: "translateY(-20px)" },
                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                    "pulse-glow": {
                                                                                                                                                                                                                                                                                                                                                                                              "0%, 100%": { opacity: "0.5" },
                                                                                                                                                                                                                                                                                                                                                                                                        "50%": { opacity: "1" },
                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                        shimmer: {
                                                                                                                                                                                                                                                                                                                                                                                                                                  "0%": { backgroundPosition: "-1000px 0" },
                                                                                                                                                                                                                                                                                                                                                                                                                                            "100%": { backgroundPosition: "1000px 0" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                            "gradient-shift": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "0%, 100%": { backgroundPosition: "0% 50%" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "50%": { backgroundPosition: "100% 50%" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "spin-slow": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "from": { transform: "rotate(0deg)" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "to": { transform: "rotate(360deg)" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          plugins: [require("tailwindcss-animate")],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default config;