"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { Terminal, X, ChevronRight, Activity } from "lucide-react";
import { clsx } from "clsx";

// --- 1. The Logic (Context) ---
type LogType = "info" | "success" | "warning" | "error";

interface LogEntry {
  id: number;
    type: LogType;
      message: string;
        timestamp: string;
        }

        interface ConsoleContextType {
          isOpen: boolean;
            toggle: () => void;
              addLog: (message: string, type?: LogType) => void;
                clear: () => void;
                }

                const ConsoleContext = createContext<ConsoleContextType | undefined>(undefined);

                export function useConsole() {
                  const context = useContext(ConsoleContext);
                    if (!context) throw new Error("useConsole must be used within ConsoleProvider");
                      return context;
                      }

                      export function ConsoleProvider({ children }: { children: React.ReactNode }) {
                        const [isOpen, setIsOpen] = useState(false);
                          const [logs, setLogs] = useState<LogEntry[]>([]);

                            const addLog = (message: string, type: LogType = "info") => {
                                const entry: LogEntry = {
                                      id: Date.now(),
                                            type,
                                                  message,
                                                        timestamp: new Date().toLocaleTimeString().split(" ")[0], // "10:45:12"
                                                            };
                                                                setLogs((prev) => [...prev, entry]);
                                                                  };

                                                                    const toggle = () => setIsOpen((prev) => !prev);
                                                                      const clear = () => setLogs([]);

                                                                        return (
                                                                            <ConsoleContext.Provider value={{ isOpen, toggle, addLog, clear }}>
                                                                                  {children}
                                                                                        {/* Render the UI directly here so it's always available */}
                                                                                              <DevConsoleUI isOpen={isOpen} logs={logs} close={() => setIsOpen(false)} />
                                                                                                  </ConsoleContext.Provider>
                                                                                                    );
                                                                                                    }

                                                                                                    // --- 2. The UI (The Visual Terminal) ---
                                                                                                    function DevConsoleUI({
                                                                                                      isOpen,
                                                                                                        logs,
                                                                                                          close,
                                                                                                          }: {
                                                                                                            isOpen: boolean;
                                                                                                              logs: LogEntry[];
                                                                                                                close: () => void;
                                                                                                                }) {
                                                                                                                  // Auto-scroll to bottom
                                                                                                                    const endRef = React.useRef<HTMLDivElement>(null);
                                                                                                                      useEffect(() => {
                                                                                                                          endRef.current?.scrollIntoView({ behavior: "smooth" });
                                                                                                                            }, [logs]);

                                                                                                                              return (
                                                                                                                                  <div
                                                                                                                                        className={clsx(
                                                                                                                                                "fixed bottom-0 left-0 right-0 z-50 transition-transform duration-500 ease-in-out border-t border-cyber-border shadow-2xl",
                                                                                                                                                        isOpen ? "translate-y-0" : "translate-y-full"
                                                                                                                                                              )}
                                                                                                                                                                  >
                                                                                                                                                                        {/* Glassmorphism Background */}
                                                                                                                                                                              <div className="absolute inset-0 bg-cyber-black/90 backdrop-blur-md" />

                                                                                                                                                                                    {/* Terminal Content */}
                                                                                                                                                                                          <div className="relative h-[300px] flex flex-col font-mono text-sm max-w-4xl mx-auto border-x border-cyber-border/30 bg-black/50">
                                                                                                                                                                                                  
                                                                                                                                                                                                          {/* Header */}
                                                                                                                                                                                                                  <div className="flex items-center justify-between p-2 border-b border-cyber-border bg-cyber-gray/50">
                                                                                                                                                                                                                            <div className="flex items-center gap-2 text-neon-blue">
                                                                                                                                                                                                                                        <Terminal className="w-4 h-4" />
                                                                                                                                                                                                                                                    <span className="font-bold tracking-wider text-xs">X-RAY_CONSOLE // LIVE_FEED</span>
                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                        <button onClick={close} className="hover:text-neon-red transition-colors">
                                                                                                                                                                                                                                                                                    <X className="w-4 h-4" />
                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                              {/* Logs Area */}
                                                                                                                                                                                                                                                                                                                      <div className="flex-1 overflow-y-auto p-4 space-y-2">
                                                                                                                                                                                                                                                                                                                                  {logs.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                  <div className="text-cyber-muted opacity-50 italic">
                                                                                                                                                                                                                                                                                                                                                                      Waiting for events...
                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                              {logs.map((log) => (
                                                                                                                                                                                                                                                                                                                                                                                                                          <div key={log.id} className="flex gap-3 animate-in fade-in slide-in-from-left-2 duration-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-cyber-muted text-[10px] mt-0.5">{log.timestamp}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex items-start gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <ChevronRight className={clsx("w-3 h-3 mt-1", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          log.type === "success" ? "text-neon-green" : 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              log.type === "error" ? "text-neon-red" : "text-neon-blue"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className={clsx(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  log.type === "success" ? "text-neon-green" : 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      log.type === "error" ? "text-neon-red font-bold" : "text-cyber-text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {log.message}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div ref={endRef} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Status Bar */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="p-1 px-4 border-t border-cyber-border text-[10px] text-cyber-muted flex justify-between bg-black">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>STATUS: ONLINE</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="flex items-center gap-1 text-neon-green">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Activity className="w-3 h-3" /> LISTENING
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }